package ee.vstepa.jetbrains.plugins.renpy.navigation

import com.intellij.codeInsight.navigation.actions.GotoDeclarationHandler
import com.intellij.openapi.components.service
import com.intellij.openapi.editor.Editor
import com.intellij.openapi.vfs.LocalFileSystem
import com.intellij.psi.PsiDocumentManager
import com.intellij.psi.PsiElement
import com.intellij.psi.PsiManager
import ee.vstepa.jetbrains.plugins.renpy.service.RenPyNavigationService
import java.io.File

class RenPyGotoDeclarationHandler : GotoDeclarationHandler {

    override fun getGotoDeclarationTargets(
        sourceElement: PsiElement?,
        offset: Int,
        editor: Editor?
    ): Array<PsiElement>? {
        if (sourceElement == null) return null

        val text = sourceElement.text.trim('"', '\'')
        if (text.isBlank()) return null

        val project = sourceElement.project
        val navService = project.service<RenPyNavigationService>()

        // Look up specifically inside labels first, then screens
        val location = navService.getLabelLocation(text) ?: navService.getScreenLocation(text) ?: return null
        var (relativePath, lineNumber) = location

        // Handle .rpyc bytecode paths generated by Ren'Py
        if (relativePath.endsWith(".rpyc")) {
            relativePath = relativePath.removeSuffix("c")
        }

        val basePath = project.basePath ?: return null
        val targetFile = File(basePath, relativePath)
        if (!targetFile.exists()) return null

        val virtualFile = LocalFileSystem.getInstance().findFileByIoFile(targetFile) ?: return null
        val psiFile = PsiManager.getInstance(project).findFile(virtualFile) ?: return null

        val document = PsiDocumentManager.getInstance(project).getDocument(psiFile) ?: return arrayOf(psiFile)
        val zeroBasedLine = (lineNumber - 1).coerceAtLeast(0)

        if (zeroBasedLine < document.lineCount) {
            val lineStartOffset = document.getLineStartOffset(zeroBasedLine)
            var targetElement = psiFile.findElementAt(lineStartOffset)

            while (targetElement != null && targetElement.text.isBlank()) {
                targetElement = targetElement.nextSibling ?: targetElement.parent?.nextSibling
            }

            if (targetElement != null) {
                return arrayOf(targetElement)
            }
        }

        return arrayOf(psiFile)
    }
}